# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WhoAmI(object):
    def setupUi(self, WhoAmI):
        WhoAmI.setObjectName("WhoAmI")
        WhoAmI.resize(400, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(WhoAmI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=WhoAmI)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.imageLabel = QtWidgets.QLabel(parent=WhoAmI)
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.imageLabel.setMinimumSize(QtCore.QSize(300, 300))
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.hintLabel = QtWidgets.QLabel(parent=WhoAmI)
        self.hintLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hintLabel.setObjectName("hintLabel")
        self.verticalLayout.addWidget(self.hintLabel)
        self.answerInput = QtWidgets.QLineEdit(parent=WhoAmI)
        self.answerInput.setObjectName("answerInput")
        self.verticalLayout.addWidget(self.answerInput)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.checkButton = QtWidgets.QPushButton(parent=WhoAmI)
        self.checkButton.setObjectName("checkButton")
        self.buttonLayout.addWidget(self.checkButton)
        self.giveUpButton = QtWidgets.QPushButton(parent=WhoAmI)
        self.giveUpButton.setObjectName("giveUpButton")
        self.buttonLayout.addWidget(self.giveUpButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.attemptsLabel = QtWidgets.QLabel(parent=WhoAmI)
        self.attemptsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.attemptsLabel.setObjectName("attemptsLabel")
        self.verticalLayout.addWidget(self.attemptsLabel)

        self.retranslateUi(WhoAmI)
        QtCore.QMetaObject.connectSlotsByName(WhoAmI)

    def retranslateUi(self, WhoAmI):
        _translate = QtCore.QCoreApplication.translate
        WhoAmI.setWindowTitle(_translate("WhoAmI", "Кто я?"))
        self.titleLabel.setText(_translate("WhoAmI", "Кто я?"))
        self.imageLabel.setText(_translate("WhoAmI", "[Фото]"))
        self.hintLabel.setText(_translate("WhoAmI", "Подсказка: [Текст подсказки]"))
        self.answerInput.setPlaceholderText(_translate("WhoAmI", "Введите ваш ответ"))
        self.checkButton.setText(_translate("WhoAmI", "Проверить ответ"))
        self.giveUpButton.setText(_translate("WhoAmI", "Сдаться"))
        self.attemptsLabel.setText(_translate("WhoAmI", "Попытки: 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WhoAmI = QtWidgets.QWidget()
    ui = Ui_WhoAmI()
    ui.setupUi(WhoAmI)
    WhoAmI.show()
    sys.exit(app.exec())
